export const teams = [
    {
        id: 1,
        title: "admin",
        description: "Admins exclusive team",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 1,
        title: "ducimus",
        description: "lorem ipsum dolor emet",
        created_at: "2020-09-14 00:00:00",
        updated_at:null,
    },
    {
        id: 1,
        title: "perferendis",
        description: "patati patata",
        created_at: "2023-02-16 00:00:00",
        updated_at:null,
    },
]

export const tasks = [
    {
        id: 1,
        category: 'peinture',
        tasker: "Jean Paul",
        creator: "Philibert TRAND",
        category_id: null,
        team_id: 1,
        assigned_to_id: 1,
        created_by_id: 1,
        title: "adminTaskTitle1",
        description: "admin Task Description 1",
        difficulty: "2",
        accept_deadline: "1984-12-02 00:12:58",
        completition_deadline: "2022-10-08 19:57:42",
        datetime_accepted: "null",
        completed: "2022-10-07 04:39:17",
        status: "en cours",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 2,
        category: 'plomberie',
        category_id: 2,
        tasker: "Jean Didier",
        creator: "Jean MIMI",
        team_id: 2,
        assigned_to_id: 13,
        created_by_id: 12,
        title: "adminTaskTitle10",
        description: "admin Task Description 10",
        difficulty: "3",
        accept_deadline: "1984-12-02 00:12:58",
        completition_deadline: "2022-10-08 19:57:42",
        datetime_accepted: "null",
        completed: "2022-10-07 04:39:17",
        status: "en cours",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 3,
        category: 'pause déjeuner',
        category_id: 1,
        tasker: "Jean Bernard",
        creator: "Bibi LONGSTO",
        team_id: 1,
        assigned_to_id: 1,
        created_by_id: 1,
        title: "adminTaskTitle12",
        description: "admin Task Description 12",
        difficulty: "1",
        accept_deadline: "2024-12-02 00:12:58",
        completition_deadline: "2026-10-08 19:57:42",
        datetime_accepted: "2022-10-06 10:57:59",
        completed: "2023-10-07 04:39:17",
        status: "terminé",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },

]

export const categories = [
    {
        id: 1,
        team_id: 1,
        name: "AdminsCategory",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 2,
        team_id: 2,
        name: "Aperiam",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 3,
        team_id: 2,
        name: "Aaliquam",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
]

export const users = [
    {
        id: 1,
        email: "cool@cool.fre",
        roles: ["ROLE_USER","ROLE_TASKER"],
        firstname:"jean",
        lastname: "eude",
        company: "OCLOCK",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 2,
        email: "yaya@yoyo.irf",
        roles: ["ROLE_USER","ROLE_GIVER"],
        firstname:"yohan",
        lastname: "pascontent",
        company: "OCLOCK",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
    {
        id: 3,
        email: "toto@toto.io",
        roles: ["ROLE_USER","ROLE_TASKER","ROLE_GIVER","ROLE_LEADER"],
        firstname:"toto",
        lastname: "tintin",
        company: "OCLOCK",
        created_at: "2021-08-13 00:00:00",
        updated_at:null,
    },
]

    export const members = [
        {
            id: 1,
            email: "cool@cool.fre",
            roles: ["TASKER"],
            firstname:"jean",
            lastname: "Besnard",
            company: "OCLOCK",
            created_at: "2021-08-13 00:00:00",
            teamTitle: "impedit",
            updated_at:null,
        },
        {
            id: 2,
            email: "yaya@yoyo.irf",
            roles: ["GIVER"],
            firstname:"yohan",
            lastname: "pascontent",
            company: "OCLOCK",
            created_at: "2021-08-13 00:00:00",
            teamTitle: "impedit",
            updated_at:null,
        },
        {
            id: 3,
            email: "toto@toto.io",
            roles: ["LEADER"],
            firstname:"toto",
            lastname: "tintin",
            company: "OCLOCK",
            created_at: "2021-08-13 00:00:00",
            teamTitle: "admin",
            updated_at:null,
        },
]